logging:
  receivers:
    webapp-receiver-1:
      type: files
      include_paths:
        - /var/log/csye6225/webapp.log
    webapp-receiver-2:
      type: files
      include_paths:
        - /var/log/csye6225/errorWebapp.log
  processors:
    webapp-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-receiver-1, webapp-receiver-2]
        processors: [webapp-processor]