name: Build and Deploy

on:
  pull_request:
    types: [closed]

jobs:
  build_image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup env variable
      run: |
          cd ./packer
          echo '${{ secrets.IAM_KEY }}' | base64 --decode | jq > dev-img-0b1250fc5338.json
          ls -al

    - name: Debug print credentials file
      run: cat ./packer/dev-img-0b1250fc5338.json


    - name: Run `packer init`
      id: initial
      run: |
          cd ./packer    
          packer init ./centosdemo.pkr.hcl

    - name: Run `packer validate`
      id: validate
      run: |
          cd ./packer
          packer validate ./centosdemo.pkr.hcl

    - name: Run Packer
      run: |
            cd ./packer
            echo '${{ vars.PACKER_SETTINGS }}' > variables.pkvars.hcl
            cat ./variables.pkrvars.hcl
            packer build -var-file=variables.pkvars.hcl .
      