name: packer

on:
  pull_request:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/centosdemo.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/centosdemo.pkr.hcl"

      - name: Run `packer format`
        id: fomrmat
        run: "packer fmt ./packer/centosdemo.pkr.hcl --check"