name: Validate and Format Packer Template

on:
  pull_request:
    branches:
      - main

jobs:
  packer_validate_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer version

      - name: Validate Packer Template
        run: packer validate ./packer/centosdemo.pkr.hcl

      - name: Format Packer Template
        run: packer fmt ./packer/centosdemo.pkr.hcl --check